# Site settings
title: 斯屹 - 骑红色自行车的少年
email: father!#$!@#$@#$wangsiyi!@#$%^&*()_net
description: # this means to ignore newlines until "baseurl:"
  骑红色自行车的男孩<br/>
  到处照照片的顽皮小伙伴<br/>
  骄傲的英语小广播员
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wangsiyi.net" # the base hostname & protocol for your site
twitter_username: gnawux
github_username:  gnawux

# Build settings
markdown: kramdown
